# Generated by Django 5.1.6 on 2025-03-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatheralert',
            name='recommendation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatheralert',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='weatheralert',
            name='alert_type',
            field=models.CharField(choices=[('storm', 'Storm'), ('flood', 'Flood'), ('extreme_temperature', 'Extreme Temperature'), ('fog', 'Dense Fog')], max_length=50),
        ),
    ]
